inherit_from: .rubocop_todo.yml

require:
  - rubocop-minitest
  - rubocop-performance

AllCops:
    EnabledByDefault: true
    TargetRubyVersion: 3.0

Bundler/GemComment:
  Enabled: false

Layout/LineLength:
  Max: 160

Layout/RedundantLineBreak:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - 'ext/ilios/extconf.rb'
    - 'test/helper.rb'

Style/IpAddresses:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

