plugins:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake
  - rubocop-on-rbs

AllCops:
    EnabledByDefault: true
    TargetRubyVersion: 3.1

Bundler/GemComment:
  Enabled: false

Bundler/GemVersion:
  Enabled: false

Gemspec/DependencyVersion:
  Enabled: false

Layout/LineLength:
  Max: 160

Layout/MultilineAssignmentLayout:
  Enabled: false

Layout/RedundantLineBreak:
  Enabled: false

Layout/SingleLineBlockChain:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Lint/EmptyBlock:
  Enabled: false

Lint/SuppressedException:
  Exclude:
    - 'ext/ilios/extconf.rb'

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Minitest/MultipleAssertions:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/AsciiComments:
  Exclude:
    - 'example/**/*'

Style/BlockComments:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Style/Copyright:
  Enabled: false

Style/DateTime:
  Enabled: false

Style/DisableCopsWithinSourceCodeDirective:
  AllowedCops:
    - Style/StringHashKeys
    - Style/GlobalVars

Style/Documentation:
  Exclude:
    - 'test/**/*'
    - 'example/**/*'
    - 'ext/ilios/extconf.rb'

Style/DocumentationMethod:
  Exclude:
    - 'test/**/*'
    - 'example/**/*'
    - 'ext/ilios/extconf.rb'

Style/FetchEnvVar:
  Enabled: false

Style/GlobalVars:
  Exclude:
    - 'ext/ilios/extconf.rb'
    - 'test/helper.rb'

Style/HashSyntax:
  EnforcedShorthandSyntax: either

Style/IpAddresses:
  Enabled: false

Style/InlineComment:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Exclude:
    - 'ext/ilios/extconf.rb'

Style/MissingElse:
  Enabled: false

Style/TopLevelMethodDefinition:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false
