module Ilios
  VERSION: String

  module Cassandra
    LOG_DISABLED: Integer
    LOG_CRITICAL: Integer
    LOG_ERROR: Integer
    LOG_WARN: Integer
    LOG_INFO: Integer
    LOG_DEBUG: Integer
    LOG_TRACE: Integer

    def self.log_level: (Integer log_level) -> self

    class Cluster
      PROTOCOL_VERSION_V1: Integer
      PROTOCOL_VERSION_V2: Integer
      PROTOCOL_VERSION_V3: Integer
      PROTOCOL_VERSION_V4: Integer
      PROTOCOL_VERSION_V5: Integer
      PROTOCOL_VERSION_DSEV1: Integer
      PROTOCOL_VERSION_DSEV2: Integer

      CONSISTENCY_ANY: Integer
      CONSISTENCY_ONE: Integer
      CONSISTENCY_TWO: Integer
      CONSISTENCY_THREE: Integer
      CONSISTENCY_QUORUM: Integer
      CONSISTENCY_ALL: Integer
      CONSISTENCY_LOCAL_QUORUM: Integer
      CONSISTENCY_EACH_QUORUM: Integer
      CONSISTENCY_SERIAL: Integer
      CONSISTENCY_LOCAL_SERIAL: Integer
      CONSISTENCY_LOCAL_ONE: Integer

      def connect: () -> Ilios::Cassandra::Session
      def hosts: (Array[String]) -> self
      def port: (Integer) -> self
      def keyspace: (String) -> self
      def protocol_version: (Integer) -> self
      def connect_timeout: (Integer) -> self
      def request_timeout: (Integer) -> self
      def resolve_timeout: (Integer) -> self
      def constant_speculative_execution_policy: (Integer, Integer) -> self
      def credentials: (String, String) -> self
      def consistency: (Integer | Symbol) -> self
      def serial_consistency: (Integer | Symbol) -> self
      def num_threads_io: (Integer) -> self
      def queue_size_io: (Integer) -> self
      def core_connections_per_host: (Integer) -> self
      def constant_reconnect: (Integer) -> self
      def exponential_reconnect: (Integer, Integer) -> self
      def tcp_nodelay: (bool) -> self
      def tcp_keepalive: (bool, Integer) -> self
      def connection_heartbeat_interval: (Integer) -> self
      def connection_idle_timeout: (Integer) -> self
      def load_balance_round_robin: () -> self
      def load_balance_dc_aware: (String) -> self
      def token_aware_routing: (bool) -> self
      def latency_aware_routing: (bool) -> self
      def use_schema: (bool) -> self
    end

    class Session
      def prepare_async: (String) -> Ilios::Cassandra::Future
      def prepare: (String) -> Ilios::Cassandra::Statement

      def execute_async: (Ilios::Cassandra::Statement) -> Ilios::Cassandra::Future
      def execute: (Ilios::Cassandra::Statement) -> Ilios::Cassandra::Result
    end

    class Statement
      def bind: (Hash[Symbol | String, untyped]) -> self
      def page_size=: (Integer) -> self
      def idempotent=: (bool) -> self
    end

    class ExecutionError < StandardError
      def code: () -> Integer?
    end

    class ConnectError < StandardError
      def code: () -> Integer?
    end

    class StatementError < StandardError
      def code: () -> Integer?
    end

    class Future
      def on_success: () { (Ilios::Cassandra::Result | Ilios::Cassandra::Statement) -> void } -> self
      def on_failure: () { (Ilios::Cassandra::ExecutionError) -> void } -> self
      def await: () -> self
    end

    class Result
      type row_type = Hash[String, untyped]

      include Enumerable[row_type]

      def each: () { (row_type) -> void } -> void
              | () -> ::Enumerator[row_type, self]
      def next_page: () -> (Ilios::Cassandra::Result | nil)
    end
  end
end
