name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test-linux-cassandra4:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        ruby-version: ['3.0', '3.1', '3.2']

    name: Linux, Cassandra 4, Ruby ${{ matrix.ruby-version }}
    steps:
    - name: Start Cassandra v4
      run: |
        docker run --name cassandra -d -p 9042:9042 cassandra:4
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Prepare tests
      run: bundle exec rake compile
    - name: Run tests
      run: bundle exec rake test

  test-linux-cassandra3:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    strategy:
      matrix:
        ruby-version: ['3.0', '3.1', '3.2']

    name: Linux, Cassandra 3, Ruby ${{ matrix.ruby-version }}
    steps:
    - name: Start Cassandra v3
      run: |
        docker run --name cassandra -d -p 9042:9042 cassandra:3
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Prepare tests
      run: bundle exec rake compile
    - name: Run tests
      run: bundle exec rake test

  test-macos:
    runs-on: macos-latest
    timeout-minutes: 10

    strategy:
      matrix:
        ruby-version: ['3.0', '3.1', '3.2']

    name: macOS, Cassandra 4, Ruby ${{ matrix.ruby-version }}
    steps:
    - name: Start Cassandra v4
      run: |
        brew install cassandra && cassandra
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true
    - name: Prepare tests
      run: bundle exec rake compile
    - name: Wait until Cassandra is stable
      run: sleep 30
    - name: Run tests
      run: bundle exec rake test
