name: Valgrind

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  TESTOPTS: --verbose

jobs:
  ruby-versions:
    uses: ruby/actions/.github/workflows/ruby_versions.yml@master
    with:
      engine: cruby

  valgrind:
    needs: ruby-versions
    runs-on: ubuntu-latest

    name: memcheck (Ruby ${{ needs.ruby-versions.outputs.latest }})
    timeout-minutes: 30
    strategy:
      fail-fast: false
      matrix:
        cassandra-version: ['5']
    steps:
      - name: Start Cassandra v${{ matrix.cassandra-version }}
        run: |
          docker run --name cassandra -d -p 9042:9042 cassandra:${{ matrix.cassandra-version }}
      - name: Start Cassandra v${{ matrix.cassandra-version }} with authentication
        run: |
          docker run --name cassandra-auth -d -p 9043:9042 -e MAX_HEAP_SIZE=512M -e HEAP_NEWSIZE=100M cassandra:${{ matrix.cassandra-version }} bash -c "sed -i 's/^authenticator:.*/authenticator: PasswordAuthenticator/' /etc/cassandra/cassandra.yaml && exec docker-entrypoint.sh cassandra -f"
      - uses: actions/checkout@v7
      - name: Install Valgrind
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ needs.ruby-versions.outputs.latest }}
          bundler-cache: true
      - name: Prepare tests
        run: bundle exec rake compile
      - name: Run the test suite under Valgrind memcheck
        run: bundle exec rake test:valgrind
